name: GitHub Actions Demo

on:
  push:
     branches: main
     paths-ignore: [.github/**]
  pull_request:
      branches: main
  schedule:
    - cron : '15 6 * * 0'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print event and branch info
        run: |
          echo "The job was triggered by event: ${{ github.event_name }}"
          echo "The name of your branch is ${{ github.ref }}"

      - name : Checkout repository
        uses : actions/checkout@v4.2.2

      - name : List files in repository
        run : |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
    
    
     
    
    
  
